services:
    swiftmailer.spool.smart_information_systems_spool:
        class: SmartInformationSystems\EmailBundle\Spool\EntitySpool
        arguments:
            - '@smart_information_systems_email.mailer.configuration_container'
            - '@doctrine.orm.entity_manager'
    swiftmailer.mailer.default.spool.smart_information_systems_spool:
        alias: swiftmailer.spool.smart_information_systems_spool

    smart_information_systems_email.mailer.configuration_container:
        class: SmartInformationSystems\EmailBundle\Service\Mailer\ConfigurationContainer
    sis_mailer:
        class: SmartInformationSystems\EmailBundle\Service\Mailer
        arguments:
            - '@smart_information_systems_email.mailer.configuration_container'
            - '@mailer'
            - '@twig'
